n_input_modal: 3
name: PT-GAN
num_threads: 2
save_visual_freq: 50
batch_size: 1
checkpoints_dir: ./checkpoints
continue_train: False
dataroot: ../data/SISS2015_Training
test_dataroot: ../data/ISLES2015_SISS_Testing
dataset: isles
epoch: latest
epoch_count: 1
gan_mode: vanilla
gpu_ids: [0]
init_gain: 0.02
init_type: normal
input_nc: 1
isTrain: True
lambda_GP: 0.1
lambda_L1: 100.0
lambda_bce: 5
load_iter: 0
lr: 0.0002
lr_decay_iters: 50
lr_policy: linear
max_dataset_size: 1000000
model: PT_GAN
n_epochs: 500
n_epochs_decay: 0
ndf: 64
ngf: 64
no_dropout: False
norm: batch
output_nc: 1
print_freq: 100
save_epoch_freq: 50
save_latest_freq: 5000
serial_batches: False
update_freq: 1000
verbose: False