n_input_modal: 4
name: PT-GAN
num_threads: 2
save_visual_freq: 50
batch_size: 1
checkpoints_dir: ./checkpoints
continue_train: False
crop_size: 256
dataroot: ../data/MultiPIE_Illumination_crop_divide/train
test_dataroot: ../data/MultiPIE_Illumination_crop_divide/test
dataset: multipie
epoch: latest
epoch_count: 1
gan_mode: vanilla
gpu_ids: [0]
init_gain: 0.02
init_type: normal
input_nc: 3
isTrain: True
lambda_GP: 0.1
lambda_L1: 100.0
lambda_bce: 5
load_iter: 0
load_size: 286
lr: 0.0002
lr_decay_iters: 50
lr_policy: linear
max_dataset_size: 1000000
model: PT_GAN
n_epochs: 300
n_epochs_decay: 0
ndf: 64
ngf: 64
no_dropout: False
no_flip: False
norm: batch
output_nc: 3
print_freq: 100
preprocess: resize_and_crop
save_epoch_freq: 50
save_latest_freq: 5000
serial_batches: False
update_freq: 1000
verbose: False