n_input_modal: 7
name: PT-GAN
dataroot: ../data/RaFD090Crop
dataset: rafd
targetp: ['28', '47', '53', '57', '70', '73']
save_visual_freq: 50
model: PT_GAN
input_nc: 3
output_nc: 3
batch_size: 1
checkpoints_dir: ./checkpoints
continue_train: False
crop_size: 256
epoch: latest
epoch_count: 1
gan_mode: vanilla
gpu_ids: [0]
init_gain: 0.02
init_type: normal
isTrain: True
lambda_GP: 0.1
lambda_L1: 100.0
lambda_bce: 5
load_iter: 0
load_size: 286
lr: 0.0002
lr_decay_iters: 50
lr_policy: linear
max_dataset_size: 1000000
n_epochs: 300
n_epochs_decay: 0
ndf: 64
ngf: 64
no_dropout: False
no_flip: False
norm: batch
num_threads: 2
preprocess: resize_and_crop
print_freq: 100
save_epoch_freq: 50
save_latest_freq: 5000
serial_batches: False
update_freq: 1000
verbose: False